require("plugins.config.colorscheme")
require("plugins.config.treesitter")
require("plugins.config.nvim-tree")
require("plugins.config.comments")
require("plugins.config.lualine")
require("plugins.config.autopairs")
require("plugins.config.indetation")
